Assignment 4.1 + 2

In [199]:
import numpy as np
class BingoGame:
    def __init__(self, BingoCards, OrderOfDrawnNumbers):
        self.BingoCards = BingoCards
        self.OrderOfDrawnNumbers = OrderOfDrawnNumbers
        self.winner = []
        self.winningNumber = None
    def Play(self):
        completedCards = 0
        for number in self.OrderOfDrawnNumbers:
            for card in self.BingoCards:
                if card.rank == None:
                    card.MarkNumber(number)

            roundCards = 0
            for card in self.BingoCards:
                
                if card.rank == None:
                    if card.IsComplete():
                        
                        if completedCards == 0:
                            self.winningNumber = number
                            self.winner.append(card)
                        card.rank = completedCards+1
                        card.winning_number  = number
                        # print(f"{card.Name} is placed {card.rank}")
                        roundCards += 1
            completedCards += roundCards

            # Game is over
            if completedCards == len(self.BingoCards):
                break
            
        return self.winner

class BingoCard:
    def __init__(self, card_numbers):
        # split all the 
        self.board = card_numbers
        self.marked_numbers = np.zeros([5,5])
        self.rank = None
        self.winning_number = None

    def MarkNumber(self, number):
        location = self.LocationOnBoard(number)
        if (location != None):
            self.marked_numbers[location[0]][location[1]] = 1
    
    def IsComplete(self):
        # row is complete
        for i in range(5):
            if (self.marked_numbers[i][0] == 1 
            and self.marked_numbers[i][1] == 1 
            and self.marked_numbers[i][2] == 1 
            and self.marked_numbers[i][3] == 1 
            and self.marked_numbers[i][4] == 1):
                return True
        # column is complete
            if (self.marked_numbers[0][i] == 1 
            and self.marked_numbers[1][i] == 1 
            and self.marked_numbers[2][i] == 1 
            and self.marked_numbers[3][i] == 1 
            and self.marked_numbers[4][i] == 1):
                return True

    def LocationOnBoard(self, number):
        for i in range(5):
            for j in range(5):
                if self.board[i][j] == number:
                    return [i,j]
        return None

    # Get Completed Row or Column
    def GetCompletedRowOrColumn(self):
        for i in range(5):
            if (self.marked_numbers[i][0] == 1 
            and self.marked_numbers[i][1] == 1 
            and self.marked_numbers[i][2] == 1 
            and self.marked_numbers[i][3] == 1 
            and self.marked_numbers[i][4] == 1):
                return self.board[i]

            if (self.marked_numbers[0][i] == 1 
            and self.marked_numbers[1][i] == 1 
            and self.marked_numbers[2][i] == 1 
            and self.marked_numbers[3][i] == 1 
            and self.marked_numbers[4][i] == 1):
                return [self.board[0][i], self.board[1][i], self.board[2][i], self.board[3][i], self.board[4][i]]
        return None
    # Sum all unmarked numbers
    def SumUnmarkedNumbers(self):
        sum = 0
        for i in range(5):
            for j in range(5):
                if self.marked_numbers[i][j] == 0:
                    sum += self.board[i][j]
        return sum
def GetBingo():
    data = []
    with open('./data/aoc4.txt') as f:
        data = f.readlines()

    # remove \n from each row
    data = [x.strip() for x in data]

    # first line the order of numbers comma separated
    order = data[0].split(',')
    order = [int(x) for x in order]
    # remove the first line
    data.pop(0)
    # remove line if equal to ''
    data = [x for x in data if x != '']
    # Create a list of bingo cards
    bingo_cards = []
    # Create a list of bingo cards
    for i in range(int(len(data)/5)):
        board = data[i*5:i*5+5]
        # split numbers in each row
        board = [x.split(' ') for x in board]
        # remove empty strings from each row
        board = [[int(x) for x in y if x != ''] for y in board]
        # convert to int
        board = [[int(x) for x in y] for y in board]
        bingo_cards.append(BingoCard(board))
        bingo_cards[i].Name = f"Card {i+1}"

    return BingoGame(bingo_cards, order)

bingo_game =GetBingo()

winning_cards = bingo_game.Play()


print(f"{len(winning_cards)} cards won")
# print winning cards
for card in winning_cards:
    print(card.Name)
    print(card.rank)
    print(card.board)
    print(card.marked_numbers)
    print(card.GetCompletedRowOrColumn())
    print(f"value: {card.SumUnmarkedNumbers() * card.winning_number}")

weakest_card = winning_cards[0]
# get the card with the lowest rank
for card in bingo_game.BingoCards:
    if card.rank > weakest_card.rank:
        weakest_card = card

print(weakest_card.Name)
print(weakest_card.rank)
print(weakest_card.board)
print(weakest_card.marked_numbers)
print(weakest_card.GetCompletedRowOrColumn())
print(f"value: {weakest_card.SumUnmarkedNumbers() * weakest_card.winning_number}")

1 cards won
Card 82
1
[[18, 30, 28, 50, 81], [67, 47, 41, 45, 59], [51, 14, 92, 6, 68], [8, 46, 69, 84, 13], [93, 25, 58, 26, 75]]
[[1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1.]]
[30, 47, 14, 46, 25]
value: 8442
Card 69
100
[[48, 66, 23, 26, 15], [16, 76, 81, 10, 49], [57, 74, 68, 67, 98], [43, 31, 53, 94, 86], [80, 71, 85, 0, 33]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1.]
 [0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1.]]
[48, 66, 23, 26, 15]
value: 4590
