Assignment 9

In [3]:
import numpy as np
import cv2


# Minimum point checks if in a 3x3 grid the center value is less than the values left, right, top and bottom
def IsMinimumPoint(area):
    if area[1, 1] < area[0, 1] and area[1, 1] < area[2, 1] and area[1, 1] < area[1, 0] and area[1, 1] < area[1, 2]:
        return True
    else:
        return False


# Get the area of the image of from the document
def GetArea(dataset):
    data = []
    with open(dataset, 'r') as f:
        data = f.readlines()
    
    # strip the new line character
    data = [x.strip() for x in data]


    

    return data

data = GetArea('./data/aoc9.txt')


# create a np array of value 10 
area = np.full((len(data)+2, len(data[0])+2), 9, dtype=np.uint8)

areaclean = np.full((len(data), len(data[0])), 0, dtype=np.uint8)

# add the data to the center area
for i in range(len(data)):
    for j in range(len(data[i])):
        area[i+1, j+1] = int(data[i][j])
for i in range(len(data)):
    for j in range(len(data[i])):
        areaclean[i, j] = int(data[i][j])

# use the minimum point to create a new array 
Image = np.zeros((len(area ), len(area[0])), dtype=np.uint8)

for i in range(1,len(area)):
    for j in range(1,len(area[i])):
        if IsMinimumPoint(area[i-1:i+2, j-1:j+2]):
            Image[i, j] = area[i, j] +1
            #print(f"{i}, {j}")
            #print(data[i-1:i+2, j-1:j+2])
            #print(Image[i-1:i+2, j-1:j+2])



print(Image)
# sum all the values in the image
print(np.sum(Image))

# scale gray image
areaclean = areaclean* (255/np.max(areaclean))
cv2.imwrite('./images/aoc9_area.bmp', areaclean)

Image = Image* (255/np.max(Image))
cv2.imwrite('./images/aoc9_lowpoints.bmp', Image)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
588


True

In [4]:
area = np.full((len(data), len(data[0])), 0, dtype=np.uint8)

for i in range(len(data)):
    for j in range(len(data[i])):
        area[i, j] = int(data[i][j])

basin = np.full((len(data), len(data[0])), 0, dtype=np.uint8)
scanmask = np.full((len(data), len(data[0])), 0, dtype=np.uint8)
# for all pixels, if pixel is 9 then it is a basin pixel
for i in range(0,len(area)):
    for j in range(0,len(area[i])):
        if area[i, j] < 9:
            basin[i, j] = 1
        else:
            scanmask[i, j] = 1

def ScanCount(basin, i, j, scanmask):
    if basin[i, j] == 0:
        return 0
    else:
        scanmask[i, j] = 1
        count = 1
        if i > 0:
            if scanmask[i-1, j] == 0:
                count += ScanCount(basin, i-1, j, scanmask)
        if i < len(basin)-1:
            if scanmask[i+1, j] == 0:
                count += ScanCount(basin, i+1, j, scanmask)
        
        if j > 0:
            if scanmask[i, j-1] == 0:
                count += ScanCount(basin, i, j-1, scanmask)
        if j < len(basin[i])-1:
            if scanmask[i, j+1] == 0:
                count += ScanCount(basin, i, j+1, scanmask)

        return count


BasinImage = basin* (255/np.max(basin))
cv2.imwrite('./images/aoc9_basin.bmp', BasinImage)

scanMaskImage = scanmask* (255/np.max(scanmask))
cv2.imwrite('./images/aoc9_startscanmask.bmp', scanMaskImage)

listofbasinSizes = []
for i in range(0,len(basin)):
    for j in range(0,len(basin[i])):
        if basin[i, j] == 1 and scanmask[i, j] == 0:
            listofbasinSizes.append(ScanCount(basin, i, j, scanmask))

listofbasinSizes.sort(reverse=True)


print(listofbasinSizes[0])
print(listofbasinSizes[1])
print(listofbasinSizes[2])
print(listofbasinSizes[0] * listofbasinSizes[1] * listofbasinSizes[2])


107
98
92
964712
