Assignment 20

In [86]:
import numpy as np
import cv2
import math
import sys
import time
import enum

def GetBool(char):
    if char == '#':
        return 1
    elif char =='.':
        return 0
    else:
        raise InputError("Invalid input")

def AddBorder(image, borderSize, value = 0):
    image = np.pad(image, borderSize, 'constant', constant_values=value)
    return image
def Crop(image, size):
    return image[size:-size, size:-size]

def GetIndexFromMask(mask):
    # mask to bit array
    mask = [y for x in mask for y in x]
    # bit array to int
    return int(''.join(map(str, mask)), 2)

def ApplyMasking(image, algorithm):
    new = np.zeros(image.shape, dtype=np.uint8)
    for i in range(1, len(image)-1):
        for j in range(1, len(image[i])-1):
            # get the 3x3 area of the image
            area = image[i-1:i+2, j-1:j+2]
            # get Index for the algorithm
            index = GetIndexFromMask(area)
            # apply the algorithm
            new[i,j] = algorithm[index]
            
    return new
def CountTrue(image):
    return np.sum(image)


def GetData(dataset):
    data = []
    with open(dataset, 'r') as f:
        data = f.readlines()

    
    # strip the new line character
    data = [x.strip() for x in data]

    algorithm = [GetBool(x) for x in data[0]]
    data.pop(0)
    data.pop(0)

    image = [[GetBool(y) for y in x] for x in data ]
    return algorithm, np.array(image, dtype=np.uint8)


In [87]:
algorithm, image = GetData('./data/aoc20_test.txt')
print (algorithm)
print (image)

testImage = AddBorder(image, 50*2*2)
testImage = ApplyMasking(testImage, algorithm)
newImage = ApplyMasking(testImage, algorithm)

print(CountTrue(newImage))

[0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 

In [88]:
algorithm, image = GetData('./data/aoc20.txt')
print (algorithm)
print (image)

testImage = AddBorder(image, 500)
newImage = ApplyMasking(testImage, algorithm)
testImage = AddBorder(newImage, 1)
newImage = ApplyMasking(testImage, algorithm)

crop = newImage[4:-4, 4:-4]
print(CountTrue(newImage))
print(CountTrue(crop))

[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 

In [89]:
algorithm, image = GetData('./data/aoc20_test.txt')
testImage = AddBorder(image, 50*2*2)
for i in range(50):
    testImage = ApplyMasking(testImage, algorithm)
    print (i, CountTrue(testImage))



0 24
1 35
2 53
3 63
4 88
5 103
6 137
7 145
8 185
9 207
10 252
11 271
12 338
13 350
14 400
15 442


KeyboardInterrupt: 

In [90]:
algorithm, image = GetData('./data/aoc20.txt')
#print (algorithm)
#print (image)

testImage = image.copy()
for i in range(50):
    testImage = AddBorder(testImage,2, i%2)
    print(testImage)
    testImage = ApplyMasking(testImage, algorithm)
    testImage = Crop(testImage, 1)
    print(testImage)
    print (i, CountTrue(testImage))



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 1]
 [1 0 0 ... 1 1 1]
 ...
 [1 0 0 ... 0 1 1]
 [1 0 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
0 5558
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 1 1 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
1 5359
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]]
2 6192
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
3 5563
[[0 0 0 ... 