Assignment 11

In [11]:
import numpy as np
import cv2


# Get the area of the image of from the document
def GetBeginFlashState(dataset):
    data = []
    with open(dataset, 'r') as f:
        data = f.readlines()
    # strip the new line character
    data = [x.strip() for x in data]

    # for each character in the data get int value
    for i in range(len(data)):
        data[i] = [int(x) for x in data[i]]

    return np.array(data, dtype=np.uint8)



def SimulateFlashesAndCount(data, simulation_time, breakTime):
    count = 0
    for i in range(simulation_time):
        # subtract 1 to each pixel
        dataNext = data + 1
        flash_mask = np.zeros(data.shape, dtype=np.uint8)
        # check all pixels if one is 10. If so, add 1 to their neighbours
        newflash = True
        while newflash:
            newflash = False
            for y in range(data.shape[0]):
                for x in range(data.shape[1]):
                    if dataNext[y][x] == 10 and flash_mask[y][x] == 0:
                        #print("Flash at: ", x, y)
                        flash_mask[y][x] = 1
                        dataNext[y][x] += 1
                        newflash = True
                        for yy in range(max(y-1,0), min(y+2, data.shape[0])):
                            for xx in range(max(x-1,0), min(x+2, data.shape[1])):
                                if dataNext[yy][xx] < 10:
                                    dataNext[yy][xx] += 1

        
        for y in range(data.shape[0]):
            for x in range(data.shape[1]):
                if dataNext[y][x] >=10:
                    dataNext[y][x] = 0

        count += flash_mask.sum()   
        data = dataNext

        #print("Simulation time: ", i)
        #print(data)
        if np.sum(data) < breakTime:
            count += 1
        # if breaktime is greater than 0 show the image for breaktime miliseconds
        if (breakTime>0):
            Image = np.zeros((data.shape[0]*50,data.shape[1]*50), dtype=np.uint8)
            for y in range(data.shape[0]): 
                for x in range(data.shape[1]):
                    if data[y][x] == 0:
                        Image[y*50:(y+1)*50, x*50:(x+1)*50] = 255
            #cv2.imwrite(f'./images/aoc11_[{i}].bmp', Image)
            cv2.imshow('image',Image)
            cv2.waitKey(breakTime)
    return count
            
data = GetBeginFlashState('./data/aoc11.txt')
print(data)

count = SimulateFlashesAndCount(data, 100,0)

print(f'flashcount : {count}')


[[3 1 1 3 2 8 4 8 8 6]
 [2 8 5 1 8 7 6 1 4 4]
 [2 7 7 4 6 6 4 4 8 4]
 [6 7 1 5 1 1 2 5 7 8]
 [7 1 4 6 2 7 2 1 5 3]
 [6 2 5 6 6 5 6 3 6 7]
 [3 1 4 8 6 6 6 2 4 5]
 [3 8 5 7 4 4 6 5 2 8]
 [7 3 2 2 4 2 2 8 3 3]
 [8 1 5 2 1 7 5 1 6 8]]
flashcount : 1705


In [12]:
def SimulateUntilSyncronized(data, simulation_time, breakTime):
    count = 0
    while True:
        # subtract 1 to each pixel
        dataNext = data + 1
        flash_mask = np.zeros(data.shape, dtype=np.uint8)
        # check all pixels if one is 10. If so, add 1 to their neighbours
        newflash = True
        while newflash:
            newflash = False
            for y in range(data.shape[0]):
                for x in range(data.shape[1]):
                    if dataNext[y][x] == 10 and flash_mask[y][x] == 0:
                        #print("Flash at: ", x, y)
                        flash_mask[y][x] = 1
                        dataNext[y][x] += 1
                        newflash = True
                        for yy in range(max(y-1,0), min(y+2, data.shape[0])):
                            for xx in range(max(x-1,0), min(x+2, data.shape[1])):
                                if dataNext[yy][xx] < 10:
                                    dataNext[yy][xx] += 1

        
        for y in range(data.shape[0]):
            for x in range(data.shape[1]):
                if dataNext[y][x] >=10:
                    dataNext[y][x] = 0

        count += 1  
        data = dataNext
        
        #print("Simulation time: ", i)
        #print(data)
        # if breaktime is greater than 0 show the image for breaktime miliseconds
        if (breakTime>0):
            Image = np.zeros((data.shape[0]*50,data.shape[1]*50), dtype=np.uint8)
            for y in range(data.shape[0]): 
                for x in range(data.shape[1]):
                    if data[y][x] == 0:
                        Image[y*50:(y+1)*50, x*50:(x+1)*50] = 255
            #cv2.imwrite(f'./images/aoc11_[{i}].bmp', Image)
            cv2.imshow('image',Image)
            Image = np.zeros((data.shape[0]*50,data.shape[1]*50), dtype=np.uint8)
            for y in range(data.shape[0]): 
                for x in range(data.shape[1]):
                    Image[y*50:(y+1)*50, x*50:(x+1)*50]  = data[y][x] *(255/ data.max() )
            #cv2.imwrite(f'./images/aoc11_[{i}].bmp', Image)
            cv2.imshow('image2',Image)

            cv2.waitKey(breakTime)
        if flash_mask.sum() == flash_mask.shape[0]*flash_mask.shape[1]:
            break
    return count


count = SimulateUntilSyncronized(data, 100, 100)  

print(f'stepCount : {count}')

stepCount : 265


<ipython-input-12-385e47465e71>:46: RuntimeWarning: divide by zero encountered in true_divide
  Image[y*50:(y+1)*50, x*50:(x+1)*50]  = data[y][x] *(255/ data.max() )
<ipython-input-12-385e47465e71>:46: RuntimeWarning: invalid value encountered in multiply
  Image[y*50:(y+1)*50, x*50:(x+1)*50]  = data[y][x] *(255/ data.max() )
