Assignment 24

In [84]:
import numpy as np
import cv2
import hashlib
# Get the area of the image of from the document
def GetGrid(dataset):
    data = []
    with open(dataset, 'r') as f:
        data = f.readlines()
    # strip the new line character
    data = [x.strip() for x in data]

    # for each character in the data get int value
    grid= np.zeros((len(data), len(data[0]),3), dtype=np.uint8)
    for i in range(len(data)):
        for j in range(len(data[i])):
            if data[i][j] == '.':
                grid[i][j] = [255,0,0]
            elif data[i][j] == '>':
                grid[i][j] = [0,0,255]
            elif data[i][j] == 'v':
                grid[i][j] = [0,255,0]

    return grid

def MoveEast(grid):
    newgrid = grid.copy()
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            

            if grid[i][j][2] == 255:
                test = j +1
                if test == len(grid[i]):
                    test = 0
                if grid[i][test][0]== 255:
                    newgrid[i][j] = [255,0,0]
                    newgrid[i][test] = [0,0,255]
    return newgrid


def MoveSouth(grid):
    newgrid = grid.copy()
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            

            if grid[i][j][1] == 255:
                test = i+1
                if test == len(grid):
                    test = 0
                if grid[test][j][0] == 255:
                    newgrid[i][j] = [255,0,0]
                    newgrid[test][j] = [0,255,0]
    return newgrid

def ExecuteMove(grid):
    newgrid = MoveEast(grid)
    newgrid = MoveSouth(newgrid)
    return newgrid

def showScaledColourImage(image, breaktime=0, scaling = 1, name = 'image'):
    Image = np.zeros((image.shape[0]*scaling,image.shape[1]*scaling,3), dtype=np.uint8)
    for y in range(image.shape[0]): 
        for x in range(image.shape[1]):
            Image[y*scaling:(y+1)*scaling, x*scaling:(x+1)*scaling] = image[y][x] 
    cv2.imshow(name,Image)
    cv2.waitKey(breaktime)
def saveScaledColourImage(image, scaling = 1, name = 'image'):
    Image = np.zeros((image.shape[0]*scaling,image.shape[1]*scaling,3), dtype=np.uint8)
    for y in range(image.shape[0]): 
        for x in range(image.shape[1]):
            Image[y*scaling:(y+1)*scaling, x*scaling:(x+1)*scaling] = image[y][x] 
    cv2.imwrite(name,Image)

def CheckGridSame(grid1, grid2):
    for i in range(len(grid1)):
        for j in range(len(grid1[i])):
            if grid1[i][j][0] != grid2[i][j][0] or grid1[i][j][1] != grid2[i][j][1] or grid1[i][j][2] != grid2[i][j][2]:
                return False
    return True

In [85]:
grid = GetGrid('./data/aoc25_test.txt')
i = 0
showScaledColourImage(grid, breaktime=1, scaling = 20, name= 'initial')
Last = hash(str(grid))
while True:
    newgrid= ExecuteMove(grid)
    i += 1
    if hash(str(newgrid)) == Last:
        break
    Last = hash(str(newgrid))
    grid = newgrid
    showScaledColourImage(grid, breaktime=10, scaling = 20)
print(i)

58


In [88]:
if (True):
    grid = GetGrid('./data/aoc25.txt')
    i = 0
    showScaledColourImage(grid, breaktime=1, scaling = 5, name= 'initial')
    Last = hash(str(grid))
    while True:
        newgrid= ExecuteMove(grid)
        i += 1
        if (i == 49):
            print(str(newgrid))
            saveScaledColourImage(grid, scaling = 5, name= './images/aoc25_49.bmp')
        if (i == 50):
            saveScaledColourImage(grid, scaling = 5, name= './images/aoc25_50.bmp')
        tmphash = hash(str(newgrid))
        #print(tmphash)
        if tmphash  == Last:
            if CheckGridSame( newgrid, grid):
                break
        Last = tmphash 

        
        grid = newgrid

        
        showScaledColourImage(grid, breaktime=1, scaling = 5)
    saveScaledColourImage(grid, scaling = 5, name= './images/aoc25_final.bmp')
    print(i)

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  ...
  [255   0   0]
  [  0   0 255]
  [  0   0 255]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[  0   0 255]
  [  0 255   0]
  [  0 255   0]
  ...
  [255   0   0]
  [  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]
  [  0 255   0]
  ...
  [255   0   0]
  [255   0   0]
  [  0   0 255]]

 [[  0   0 255]
  [  0 255   0]
  [  0 255   0]
  ...
  [255   0   0]
  [255   0   0]
  [  0   0 255]]]
482
